theme: jekyll-theme-dinky
title: About Me
description: You can find all my socials here and a bit of information about myself. And I link all my projects here for easy access to all my creations.:D
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
